'use client';
import {useEffect,useState,useRef} from 'react';
import Link from 'next/link';
import {usePathname} from 'next/navigation';
import {Menu,X,ChevronDown,ExternalLink,Maximize2,CalendarDays} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Dialog,DialogTrigger,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import {event,registrationOpen,registrationText,images,milestoneStatus,type Milestone,type TrackId} from '@/data/event';
const nav=[['Trang chủ','/'],['Bảng thi','/#bang-thi'],['Thể lệ','/the-le'],['Lịch trình','/lich-trinh'],['Tài liệu','/tai-lieu'],['Liên hệ','/lien-he']];
export function Header(){const [open,setOpen]=useState(false);const path=usePathname();const toggle=useRef<HTMLButtonElement>(null);const first=useRef(true);
 useEffect(()=>{setOpen(false);if(!first.current&&!location.hash){document.querySelector<HTMLElement>('h1')?.focus({preventScroll:true});}first.current=false;
 const hash=()=>{if(location.hash){const el=document.getElementById(decodeURIComponent(location.hash.slice(1)));if(el){if(el.tagName==='DETAILS')(el as HTMLDetailsElement).open=true;el.querySelectorAll('details').forEach(d=>{d.open=true;});requestAnimationFrame(()=>el.scrollIntoView({block:'start'}));}}};const timer=window.setTimeout(hash,150);window.addEventListener('hashchange',hash);return()=>{window.clearTimeout(timer);window.removeEventListener('hashchange',hash);};},[path]);
 useEffect(()=>{const close=(e:KeyboardEvent)=>{if(e.key==='Escape'&&open){setOpen(false);toggle.current?.focus();}};const resize=()=>{if(innerWidth>=768)setOpen(false);};document.addEventListener('keydown',close);window.addEventListener('resize',resize);return()=>{document.removeEventListener('keydown',close);window.removeEventListener('resize',resize);};},[open]);
 useEffect(()=>{if(!('IntersectionObserver' in window)||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.remove('reveal-pending');observer.unobserve(e.target);}}),{threshold:.12});document.querySelectorAll('[data-reveal]').forEach(el=>{if(el.getBoundingClientRect().top>innerHeight){el.classList.add('reveal-pending');observer.observe(el);}});return()=>{observer.disconnect();document.querySelectorAll('.reveal-pending').forEach(el=>el.classList.remove('reveal-pending'));};},[path]);
 return <><a className="skip-link" href="#main-content">Bỏ qua điều hướng</a><header className="event-header"><div className="header-inner"><Link className="brand" href="/" aria-label="Danang AI4Life 2026 — Trang chủ"><img src="/assets/Danang_AI4Life_Design_Assets/brand/vku-logo-original.svg" alt="VKU" width="46" height="30"/><span className="brand-name"><span className="brand-long">Danang </span>AI4Life</span><span className="year-badge">2026</span></Link><Button ref={toggle} variant="ghost" className="menu-toggle" aria-expanded={open} aria-controls="event-nav" aria-label={open?'Đóng menu điều hướng':'Mở menu điều hướng'} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</Button><nav id="event-nav" className={open?'open':''} aria-label="Điều hướng chính">{nav.map(([label,url])=>{const active=url==='/'?path==='/':url==='/#bang-thi'?path.startsWith('/bang-thi'):path===url;return <Link key={url} href={url} className={active?'active':''} aria-current={active?'page':undefined} onClick={()=>setOpen(false)}>{label}</Link>;})}</nav></div></header></>;
}
function useRegistration(){const[open,setOpen]=useState(()=>registrationOpen());useEffect(()=>{const check=()=>setOpen(registrationOpen());check();const timer=setInterval(check,60000);return()=>clearInterval(timer);},[]);return open;}
export function RegistrationStatus(){const open=useRegistration();return <div className="registration-status"><span className="badge neutral">{open?'Trong thời hạn đăng ký theo kế hoạch':'Đã kết thúc đăng ký'}</span><span>Hạn đăng ký theo kế hoạch: 30/09/2026.</span></div>;}
export function RegistrationAction({track}:{track:TrackId}){const open=useRegistration();return open?<Button asChild className="action"><a href={event.forms[track]} target="_blank" rel="noopener noreferrer">Đăng ký {track==='life'?'AI for Life':'AI Challenge'}<ExternalLink size={15}/></a></Button>:<Button className="action closed-registration" disabled>Đã kết thúc đăng ký</Button>;}
export function RegistrationFAQ(){const open=useRegistration();return <p>{open?registrationText.open:registrationText.closed}</p>;}
export function MilestoneBadge({milestone}:{milestone:Milestone}){return <span className={'badge '+(milestone.certainty==='needs_confirmation'?'warning':'planned')}>{milestoneStatus(milestone)}</span>;}
export function Disclosure({title,children,id}:{title:string;children:React.ReactNode;id?:string}){return <details id={id} className="disclosure"><summary>{title}<ChevronDown aria-hidden="true" size={18}/></summary><div className="disclosure-body">{children}</div></details>;}
export function Gallery(){return <div className="gallery-grid">{images.map(a=><article className="card gallery-card" key={a.id}><Dialog><DialogTrigger asChild><button className="gallery-thumb" aria-label={'Xem ảnh: '+a.title}><img src={a.thumbnail} alt={a.alt} width={a.width} height={a.height} loading="lazy" style={{objectFit:a.type==='Ảnh sự kiện'||a.type==='Ảnh hoạt động'?'cover':'contain'}}/><span className="image-open"><Maximize2 size={16}/> Xem ảnh</span></button></DialogTrigger><div className="gallery-copy"><span className="badge">Mùa {a.year}</span><h3>{a.title}</h3><p className="small">{a.usage}</p><a className="text-link" href={a.sourceUrl} target="_blank" rel="noopener noreferrer">Nguồn <ExternalLink size={14}/></a></div><DialogContent className="poster-modal" showCloseButton={false}><div className="modal-top"><DialogTitle>{a.title}</DialogTitle><DialogClose asChild><Button variant="outline" className="action close-modal"><X size={16}/>Đóng</Button></DialogClose></div><img className="poster-image" src={a.path} alt={a.alt} width={a.width} height={a.height}/><DialogDescription>Mùa {a.year} · {a.type}. Tư liệu lịch sử, không áp dụng mặc định cho mùa 2026.</DialogDescription><div className="actions"><a className="text-link" href={a.path} target="_blank" rel="noopener noreferrer">Mở ảnh gốc <ExternalLink size={14}/></a><a className="text-link" href={a.sourceUrl} target="_blank" rel="noopener noreferrer">Nguồn <ExternalLink size={14}/></a></div></DialogContent></Dialog></article>)}</div>;}
export function HeroRegistration(){const open=useRegistration();return <Link className="action primary" href="/#bang-thi">{open?'Chọn bảng thi để đăng ký':'Khám phá hai bảng thi'}</Link>;}
export function MobileContents({items}:{items:[string,string][]}){return <div className="mobile-toc"><Disclosure title="Mục lục"><nav aria-label="Mục lục">{items.map(([id,label])=><a key={id} href={'#'+id}>{label}</a>)}</nav></Disclosure></div>;}
